ZPM.Net/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using ZPM.NetDb;
using ZPM.NetDb.Models;
using System.Text;

namespace ZPM.Net.Controllers
{
    [Authorize]
    public class ContactController : ZpmDataViewController
    {
        private ZpmDemoContext db = new ZpmDemoContext();
        public const int MaxListCount = 5000;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult ContactView()
        {
            var customers = db.Customers.Select(r => new IntValueOption() { value = r.CustomerId, text = r.CustomerName }).OrderBy(r=> r.text).ToList();
            ViewBag.CustomerOptions = HtmlOptions(customers);
            return View(db.Contacts.OrderBy(r => r.LastName).ThenBy(r=> r.FirstName).ThenBy(r=>r.MiddleName).ToList());
        }

        [HttpPost]
        public ActionResult GetModel(int id)
        {
            var model = db.Contacts.Where(r => r.ContactId == (int)id).SingleOrDefault();
            var ccList = db.CustomerContacts.Where(r => r.ContactId == id).Select(r=> r.CustomerId).ToList();

            Dictionary<string, object> data = ConvertToDictionary(model);
            data["CustomerIds"] = ccList;
            return Json(data);
        }

        [HttpPost]
        public JsonResult AddModel()
        {
            var model = new Contact();
            return Json(model);
        }

        [HttpPost]
        public JsonResult SaveModel(ContactForm form)
        {
            DateTime updateTime = DateTime.Now;

            SaveReturn saveReturn = new SaveReturn();
            if (form == null)
            { // sanity check, shouldn't happen
                saveReturn.Messages.Add(new SaveMessage(SaveMessageType.Error,
                                                        SaveMessageDelivery.MessageLine,
                                                        "Data error, value is null"));
            }

            if (!saveReturn.HasErrors)
            {
                Contact model;

                if (form.ContactId == 0)
                { // new category
                    model = new Contact();
                    BindFormToDbModel(form, model, saveReturn, updateTime);
                    if (!saveReturn.HasErrors)
                    {
                        model.CreatedById = model.ChangedById;
                        model.CreatedDttm = model.ChangedDttm;
                        db.Contacts.Add(model);
                        try
                        {
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            if (IsDuplicateKey(ex))
                            {
                                // display a message that tells the user what the duplicate field is
                                saveReturn.Messages.Add(new SaveMessage(SaveMessageType.Error,
                                                                        SaveMessageDelivery.MessageLine,
                                                                        "Duplicate contact name"));
                            }
                            else
                                throw;
                        }
                    }
                }
                else
                { // existing
                    model = db.Contacts.Where(r => r.ContactId == form.ContactId).SingleOrDefault();
                    BindFormToDbModel(form, model, saveReturn, updateTime);
                    if (!saveReturn.HasErrors)
                        db.SaveChanges();
                }

                if (!saveReturn.HasErrors)
                 {
                    var ccList = db.CustomerContacts.Where(r => r.ContactId == model.ContactId).ToList();

                    if (form.CustomerIds != null)
                    {
                        foreach (var id in form.CustomerIds)
                        {
                            if (id != 0) // 0 is handled by web client
                            {
                                var cc = ccList.Find(r => r.CustomerId == id);
                                if (cc == null)
                                {  // add
                                    cc = new CustomerContact()
                                    { CustomerId = id, ContactId = model.ContactId, CreatedById = User.Identity.GetUserId<int>(), CreatedDttm = updateTime };
                                    db.CustomerContacts.Add(cc);
                                }
                                else
                                {
                                    ccList.Remove(cc);
                                }
                            }
                        }
                    }
                    db.CustomerContacts.RemoveRange(ccList);
                    db.SaveChanges();
                }

                if (!saveReturn.HasErrors)
                {
                    var ccList = db.CustomerContacts.Where(r => r.ContactId == model.ContactId).Select(r => r.CustomerId).ToList();
                    Dictionary<string, object> data = ConvertToDictionary(model);
                    data["CustomerIds"] = ccList;
                    saveReturn.Model = data; // model to re-display
                }
            }
            return Json(saveReturn);
        }

        public class ContactForm
        {
            public int ContactId { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string LastName { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string FirstName { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string MiddleName { get; set; }
            public bool UseCustomerAddress { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string Address { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string City { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string State { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string ZipCode { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string PhoneNumber { get; set; }
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string Email { get; set; }
            public int CreatedById { get; set; }
            public int ChangedById { get; set; }
            public DateTime CreatedDttm { get; set; }
            public DateTime ChangedDttm { get; set; }

            public int[] CustomerIds { get; set; }
        }

        private void BindFormToDbModel(ContactForm form, Contact model, SaveReturn saveReturn, DateTime updateTime)
        {
            model.LastName = VerifyNotBlank(saveReturn, form.LastName, "LastName", "Last Name");
            model.FirstName = form.FirstName;
            model.MiddleName = form.MiddleName;
            model.UseCustomerAddress = form.UseCustomerAddress;
            model.Address = form.Address;
            model.City = form.City;
            model.State = form.State;
            model.ZipCode = form.ZipCode;
            model.PhoneNumber = form.PhoneNumber;
            model.Email = form.Email;
            model.ChangedById = User.Identity.GetUserId<int>();
            model.ChangedDttm = updateTime;
    }

    public ActionResult DeleteModel(int id)
        {
            var model = db.Contacts.Where(r => r.ContactId == id).SingleOrDefault();
            if (model == null)
                return Json("ContactId " + id.ToString() + " not found");

            db.Database.ExecuteSqlCommand("DELETE FROM CustomerContacts where ContactId=@p0", id);

            db.Contacts.Remove(model);
            db.SaveChanges();
            return Json("");
        }

    }
}

ZPM.Net/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using ZPM.NetDb;
using ZPM.NetDb.Models;
using System.Threading.Tasks;
using System.Text;

namespace ZPM.Net.Controllers
{
    [Authorize]
    public class CustomerController : ZpmDataViewController
    {
        private ZpmDemoContext db = new ZpmDemoContext();
        public const int MaxListCount = 5000;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult CustomerView()
        {
            ViewBag.ContactOptions = HtmlContactOptions();
            return View(db.Customers.OrderBy(r => r.CustomerName).ToList());
        }

        [HttpPost]
        public ActionResult ContactOptions()
        {
            return Json(HtmlContactOptions());
        }

        private string HtmlContactOptions()
        {
            var contacts = db.Contacts.Select(r => new IntValueOption()
            {
                value = r.ContactId,
                text = r.LastName + (r.FirstName != "" ? ", " + r.FirstName : "") + (r.MiddleName != "" ? " " + r.MiddleName : "")
            }).OrderBy(r => r.text).ToList();
            return HtmlOptions(contacts);
        }

        [HttpPost]
        public ActionResult GetModel(int id)
        {
            var model = db.Customers.Where(r => r.CustomerId == (int)id).SingleOrDefault();
            var ccList = db.CustomerContacts.Where(r => r.CustomerId == id).Select(r => r.ContactId).ToList();

            Dictionary<string, object> data = ConvertToDictionary(model);
            data["ContactIds"] = ccList;
            return Json(data);
        }

        [HttpPost]
        public ActionResult ReloadCustomerContacts(int customerId)
        {
            var data = new Dictionary<string, object>();
            data["Options"] = HtmlContactOptions();
            data["Values"] = db.CustomerContacts.Where(r => r.CustomerId == customerId).Select(r => r.ContactId).ToList();
            return Json(data);
        }

        [HttpPost]
        public JsonResult AddModel()
        {
            var cust = new Customer();
            cust.State = "MN";
            return Json(cust);
        }

        [HttpPost]
        public JsonResult SaveModel(CustomerForm form)
        {
            DateTime updateTime = DateTime.Now;
            SaveReturn saveReturn = new SaveReturn();

            if (form == null)
            {
                saveReturn.Messages.Add(new SaveMessage(SaveMessageType.Error,
                                                        SaveMessageDelivery.MessageLine,
                                                        "Data error, value is null"));
            }

            if (!saveReturn.HasErrors)
            {
                Customer cust;

                if (form.CustomerId == 0)
                { // new customer
                    cust = new Customer();
                    BindFormToDbModel(form, cust, saveReturn, updateTime);
                    if (!saveReturn.HasErrors)
                    {
                        cust.CreatedById = cust.ChangedById;
                        cust.CreatedDttm = cust.ChangedDttm;
                        db.Customers.Add(cust);
                        try
                        {
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            if (IsDuplicateKey(ex))
                            {
                                saveReturn.Messages.Add(new SaveMessage(SaveMessageType.Error,
                                                                        SaveMessageDelivery.MessageLine,
                                                                        "Duplicate Customer Name"));
                            }
                            else
                                throw Zpm.GetInnerException(ex);
                        }
                    }
                }
                else
                { // existing
                    cust = db.Customers.Where(r => r.CustomerId == form.CustomerId).SingleOrDefault();
                    BindFormToDbModel(form, cust, saveReturn, updateTime);
                    if (!saveReturn.HasErrors)
                        db.SaveChanges();
                }

                if (!saveReturn.HasErrors)
                {
                    var ccList = db.CustomerContacts.Where(r => r.CustomerId == cust.CustomerId).ToList();

                    if (form.ContactIds != null)
                    {
                        foreach (var id in form.ContactIds)
                        {
                            var cc = ccList.Find(r => r.ContactId == id);
                            if (cc == null)
                            {  // add
                                cc = new CustomerContact()
                                { CustomerId = cust.CustomerId, ContactId = id, CreatedById = User.Identity.GetUserId<int>(), CreatedDttm = updateTime };
                                db.CustomerContacts.Add(cc);
                            }
                            else
                            {
                                ccList.Remove(cc);
                            }
                        }
                    }
                    db.CustomerContacts.RemoveRange(ccList);
                    db.SaveChanges();
                }

                if (!saveReturn.HasErrors)
                {
                    var ccList = db.CustomerContacts.Where(r => r.CustomerId == cust.CustomerId).Select(r => r.ContactId).ToList();
                    Dictionary<string, object> data = ConvertToDictionary(cust);
                    data["ContactIds"] = ccList;
                    saveReturn.Model = data; // model to re-display
                }
            }
            return Json(saveReturn);
        }

        public class CustomerForm
        {
            public int CustomerId { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string CustomerName { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string Address { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string City { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string State { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string ZipCode { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string PhoneNumber { get; set; }

            [DisplayFormat(ConvertEmptyStringToNull = false)]
            public string Email { get; set; }

            public int? CustomerCategoryId { get; set; }
            public decimal CreditLimit { get; set; }
            public DateTime? ReviewDate { get; set; }
            public bool Statement { get; set; }
            public int[] ContactIds { get; set; }
        }

        private void BindFormToDbModel(CustomerForm form, Customer model, SaveReturn saveReturn, DateTime updateTime)
        {
            model.CustomerName = VerifyNotBlank(saveReturn, form.CustomerName, "CustomerName", "Customer Name");
            model.Address = form.Address;
            model.City = form.City;
            model.State = form.State;
            model.ZipCode = form.ZipCode;
            model.PhoneNumber = form.PhoneNumber;
            model.Email = form.Email;
            model.CustomerCategoryId = Zpm.NullIfZero(form.CustomerCategoryId);
            model.CreditLimit = form.CreditLimit;
            model.ReviewDate = form.ReviewDate;
            model.Statement = form.Statement;
            model.ChangedById = User.Identity.GetUserId<int>();
            model.ChangedDttm = updateTime;
        }

        public ActionResult DeleteModel(int id)
        {
            var cust = db.Customers.Where(r => r.CustomerId == id).SingleOrDefault();
            if (cust == null)
                return Json("CustomerId " + id.ToString() + " not found");

            db.Database.ExecuteSqlCommand("DELETE FROM CustomerContacts where CustomerId=@p0", id);

            db.Customers.Remove(cust);
            db.SaveChanges();
            return Json("");
        }

    }
}

ZPM.Net/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
@using ZPM.NetDb.Models

<!--
x@inject SignInManager<ApplicationUser>SignInManager
x@inject UserManager<ApplicationUser>UserManager
-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZPM.Net Demo</title>

    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css"/>
    <link rel="stylesheet" href="~/Content/css/site.css" />
    <link rel="stylesheet" href="~/Content/css/zpm.css" />
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css"/>
    <link rel="stylesheet" href="/Content/css/zpm.css" />

    <link href='~/scripts/smartmenus/css/sm-core-css.css' rel="stylesheet" type="text/css" />
    <link href='~/scripts/smartmenus/css/sm-blue/sm-blue.css' rel="stylesheet" type="text/css" />

    <style type="text/css">
        .sectionDivider {
            width: 100%;
            height: 6px;
            background-color: #d8d8d8;
            text-align: center;
            font-weight: bold;
        }

        #main-menu, .sm-blue a {
            background: #4b6c9e;
            background-image: linear-gradient(to bottom, #4b6c9e, #4b6c9e);
        }
    </style>

</head>
<body>
    <div class="container body-content">
        <nav role="navigation" style="padding:2px 0px;">
            <ul id="main-menu" class="sm sm-blue" style="width:100%; z-index:99;">
                <li>@Html.ActionLink("Main", "Index", "Home")</li>
                <li>
                    <a href="#">Customers</a>
                    <ul>
                        <li>@Html.ActionLink("Customers", "CustomerView", "Customer")</li>
                        <!--<li>@Html.ActionLink("Customers 2", "Customer2View", "Customer2")</li>-->
                        <li>@Html.ActionLink("Customer Categories", "CustomerCategoryView", "CustomerCategory")</li>
                        <li>@Html.ActionLink("Contacts", "ContactView", "Contact")</li>
                    </ul>
                </li>
                <li>
                    <a href="#">Reports</a>
                    <ul>
                        <li>@Html.ActionLink("Customer Reports", "CustomerReports", "CustomerReports")</li>
                        <!--<li>@Html.ActionLink("Customer 2 Reports", "Customer2Reports", "Customer2Reports")</li>-->
                        <li>@Html.ActionLink("Customer Category Reports", "CustomerCategoryReports", "CustomerCategoryReports")</li>
                    </ul>
                </li>
                <li>
                    <a href="#">Help</a>
                    <ul>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    </ul>
                </li>
                <li style="float:right">
                    @if (Request.IsAuthenticated)
                {
                    <a href="#">@User.Identity.GetUserName()</a>
                    <ul>
                        <li>
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ActionLink("Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                    }
                        </li>
                    </ul>
            }
            else
            {
                @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
        }
                </li>
            </ul>
        </nav>
        @RenderBody()
        <hr />
        <footer>
            &copy; 2018, ZPM Software Inc &nbsp; @Html.ActionLink("copyright notice", "About", "Home")
        </footer>
    </div>

    <environment include="Development">
        <script src="~/Scripts/jquery-3.3.1.js" asp-append-version="true"></script>
        <script src="~/Scripts/jquery-ui-2.12.1.js" asp-append-version="true"></script>
        <script src="~/Scripts/bootstrap.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/Scripts/jquery-3.3.1.js"  asp-append-version="true"
                asp-fallback-src="~/Scripts/jquery-3.2.1.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>  <!-- https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.js -->
        <script src="~/Scripts/jquery-ui-1.12.1.js" asp-append-version="true"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js" asp-append-version="true"
                asp-fallback-src="~/Scripts/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    <script type="text/javascript" src='~/Scripts/smartmenus/jquery.smartmenus.js' asp-append-version="true"></script>
    <script type="text/javascript">
        $('#main-menu').smartmenus({ subMenusMaxWidth: "30em" }); //activate smartmenus
        $('#main-menu').bind('click.smapi', function (e, menu) { return (menu == null || menu.className != "has-submenu highlighted"); }); // ignore click on items with sub menus

        setInterval(function () {
            $.ajax({
                type: "POST",
                url: "/Zpm/KeepSessionAlive",
                data: JSON.stringify({ dateTime: new Date().toLocaleString() }), // send time to bypass cache
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () { }
            });
        }, 300000); // every 5 min
    </script>
    <script src="~/Scripts/zpm.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>